### ISSUE TITLE
LunarClient Websocket

### ISSUE THREAD

**Issue by LuxCodeDev** [Nilsen84/lcqt2#11]
Could you add a custom websocket system?

**Comment by Nilsen84** [comment]
Are you talking about the ability to change the websocket url, or a custom websocket implementation?

**Comment by LuxCodeDev** [comment]
URL Websocket

**Comment by LuxCodeDev** [comment]
> Are you talking about the ability to change the websocket url, or a custom websocket implementation?

Change the websocket URL

**Comment by Tryflle** [comment]
But what's the point?

**Comment by LuxCodeDev** [comment]
> But what's the point?

Because that way it's like a separate server where you can have rank owner, where other players can see the cosmetics... Solar Tweaks had it and it was pretty awesome.

**Comment by Nilsen84** [comment]
Useless since there's no public websocket server.
