### ISSUE TITLE
Issue on Lunar Client Qt launch in new Lunar Launcher

### ISSUE THREAD

**Issue by ismail0vv** [Nilsen84/lcqt2#24]
When I execute Lunar Client Qt on Windows 10 OS, there is popups terminal (cmd) where it says:
[LCQT] Connecting to ws://127.0.0.1: and some more numbers
[LCQT] Sending Payload
[error] IO error: The remote host forcibly terminated the existing connection. (os error 10054)
For continue press any button . . .

PS (I have a Russian laungage as main in a system, so I just translated third line of log in Google Translator,  in English it might be not same)

And also there is no agent settings button in new lunar UI

**Comment by WhyNoNames** [comment]
bro before u launch the lunar client qt shortcut
make sure that the lunar client is closed(in the little thingy on taskbar
or it wont work
![image](https://github.com/Nilsen84/lcqt2/assets/121428695/ed178cab-16b2-4ed8-937e-f73a18ebdc32)

**Comment by ismail0vv** [comment]
Thank you bro
