### ISSUE TITLE
It has a Virus

### ISSUE THREAD

**Issue by DJMahirNationTV** [Nilsen84/lcqt2#27]
![image](https://github.com/Nilsen84/lcqt2/assets/78599090/e63a3553-1498-4ab2-81b2-1aeb9ab7fda9)

**Comment by Tryflle** [comment]
2/71 from random antiviruses i've never heard of, ah yes.
no it doesnt have a virus

**Comment by DJMahirNationTV** [comment]
Well first of all it dosent matter, there is the reason why VirusTotal included tons of AntiViruses to check from different perspectives. Here also I joined the Discord server and found that it is a mistake detection by the AntiVirus:



### **Is it a virus?**
> No, a long as you downloaded it from https://github.com/nilsen84/lcqt2 the program is entirely safe. If your antivirus believes it is a virus, that is due to the nature of the program injecting into Lunar Client and it is a false positive.
