### ISSUE TITLE
Not an issue just a request 

### ISSUE THREAD

**Issue by SumoMatch** [Nilsen84/lcqt2#3]
Can you add raw mouse input sometime thx

**Comment by AnotherPillow** [comment]
Use WeaveRawInput

**Comment by hamadaXD** [comment]
> Can you add raw mouse input sometimeis the cosmetics work with ya

**Comment by Tryflle** [comment]
> > Use WeaveRawInput
> 
> Is it for LC ?

Yea, it's a mod loader for lunar client and it has a raw input mod. In the LCQT discord, typing the command "!!weave" will give you a guide on how to set it up. 
I'm sure you can find the discord from there and install the mod from mod sharing. If not, check koxx12's github.

**Comment by hamadaXD** [comment]
whate is this?

**Comment by hamadaXD** [comment]
can u give me discord link

**Comment by SumoMatch** [comment]
> > > Use WeaveRawInput
> > 
> > Is it for LC ?
> 
> Yea, it's a mod loader for lunar client and it has a raw input mod. In the LCQT discord, typing the command "!!weave" will give you a guide on how to set it up. 
> I'm sure you can find the discord from there and install the mod from mod sharing. If not, check koxx12's github.

Yes but I need it for 1.7 and I tried but I just can't use my mouse
