### ISSUE TITLE
Not lcqt 2 issue but minecraft 1.0.0 issue pls help :(

### ISSUE THREAD

**Issue by Taimibear** [Nilsen84/lcqt2#46]
Hey guys, i wanted to play minecraft 1.0.0 but when i launch the game and then i click on create world, and the world is created it looks like this: 
![Screenshot (15)](https://github.com/Nilsen84/lcqt2/assets/142425582/452af4cd-3014-44a9-a134-1d1f81557e21)

Can someone tell me how to fix that?, why does it looks like this PLS help me guys im begging you. Sorry for posting the issue here :(

**Comment by Syz66** [comment]
yes pls fix the Minecraft 1.0.0 bug 😢😢😿😿😭😭😭

**Comment by AnotherPillow** [comment]
Oh gee I love lunar client for minecraft 1.0!!
